---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: Restart apache

- name: Check whether certificates defined in vhosts exist.
  stat:
    path: "{{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart apache
  when: apache_create_vhosts | bool

- name: Ensure httpd certs are installed (RHEL 8 and later).
  command: /usr/libexec/httpd-ssl-gencerts
  args:
    creates: /etc/pki/tls/certs/localhost.crt
  when: ansible_distribution_major_version | int >= 8

- name: Configure umask (SystemD Unit)
  lineinfile:
    path: "/usr/lib/systemd/system/{{apache_service}}.service"
    regexp: '^UMask='
    line: 'UMask={{ apache_umask }}'
    state: present
    insertafter: '^\[Service\]'
  when: ansible_service_mgr == "systemd"
  notify:
    - Reload systemd
    - Restart apache
