---
- name: Install Apache.
  package:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    update_cache: true
    # enablerepo: "{{ apache_enablerepo | default(omit, true) }}"
