---
- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}"
  become: true

- name: reload systemd
  become: true
  command: systemctl daemon-reload
