---
- name: Restart apache
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}"
  become: yes

- name: Reload systemd
  # become: yes
  # command: systemctl daemon-reload
  systemd_service:
    daemon_reload: true
