---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_listen_port_ssl: 443
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts:
      - servername: "example.com"
        documentroot: "/var/www/vhosts/example_com"

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    # RHEL7 provides `httpd-devel` in `rhel-server-rhscl-7-rpms`
    # This is not available on UBI, install from Centos repo
    # There is a version mismatch between `httpd-devel` and `httpd/mod_ssl`,
    # So I install those from centos repo also

    - name: Install dependencies from CentOS Repositories | RHEL 7+
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "7"
      block:
        - name: Define Missing Repo/Package | RHEL7
          set_fact:
            _tmp_repos:
              - name: base-centos
                url: http://mirror.centos.org/centos/7/os/x86_64/
                gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
              - name: updates-centos
                url: http://mirror.centos.org/centos/7/updates/x86_64/
                gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
            _tmp_packages:
              - name: httpd
                repo: base-centos
              - name: httpd-devel
                repo: base-centos, updates-centos
              - name: mod_ssl
                repo: base-centos, updates-centos


        - name: Add Temporary Repositories | RHEL7
          yum_repository:
            name: "{{ item.name }}"
            description: "Centos {{ ansible_distribution_major_version }} - {{ item.name }}"
            baseurl: "{{ item.url }}"
            enabled: false
            gpgkey: "{{ item.gpg }}"
          with_items: "{{ _tmp_repos }}"
          loop_control:
            label: "{{ item.name }}"

        - name: Install missing packages | RHEL7
          yum:
            name: "{{ item.name }}"
            state: present
            enablerepo: "{{ item.repo }}"
            # disable_gpg_check: true
            disablerepo: ubi-7
          with_items: "{{ _tmp_packages }}"
          loop_control:
            label: "{{ item.name }}"


  roles:
    - role: ansible-role-apache
      tags:
        - apache
