---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_listen_port_ssl: 443
    apache_create_vhosts: true
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts:
      - servername: "example.com"
        documentroot: "/var/www/vhosts/example_com"

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false


    # CentOS repository and UBI repository have mismatched versions of httpd
    # this causes and issue with httpd-devel is installed from CentOS repository
    # disabling UBI repository to force install from CentOS repository
    - name: Disable ubi-7 repository | RHEL 7
      command: yum-config-manager --disable ubi-7
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "7"




  roles:
    - role: ansible-role-apache
      tags:
        - apache
